fullnameOverride: "java-app"

application:
  probes:
    readinessProbe:
      httpGet:
        path: /api/main
        port: http
      initialDelaySeconds: 5
      periodSeconds: 15
    livenessProbe:
      httpGet:
        path: /api/main
        port: http
      initialDelaySeconds: 5
      periodSeconds: 15
      timeoutSeconds: 5
  resources:
    limits:
      cpu: "0.2"
      memory: "200Mi"
    requests:
      cpu: "0.1"
      memory: "200Mi"
  service:
    type: LoadBalancer
    port: 80
    targetPort: 8080
    protocol: TCP