fullnameOverride: "java-app"

application:
  image:
    repository: mrtanko/jenkins-java-api
    tag: "0.7"

  probes:
    readinessProbe:
      httpGet:
        path: /api/main
        port: http
      initialDelaySeconds: 400
      periodSeconds: 15
    livenessProbe:
      httpGet:
        path: /api/main
        port: http
      initialDelaySeconds: 400
      periodSeconds: 15
      timeoutSeconds: 5
  resources:
    limits:
      cpu: "0.4"
      memory: "2000Mi"
    requests:
      cpu: "0.4"
      memory: "1500Mi"
  service:
    type: LoadBalancer
    port: 80
    targetPort: 8080
    protocol: TCP
  database:
    credentialToDB: db-credential
    DB_HOST: "51.250.34.233"
    DB_PORT: "5432"
    DB_NAME: "peopledb"